@echo off
call nxjc -cp src -d bin src\org\vu\aso\next\nxt\MindstormsBrains.java
echo Compiled...
call nxjlink org.vu.aso.next.nxt.MindstormsBrains -cp bin -v -o bin\MindstormsBrains.nxj > debug.txt
echo Linked...
call nxjupload -r -b -n %1 bin\MindstormsBrains.nxj
